name: elite_assist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.0
  http: ^1.2.2
  get: ^4.6.6
  shared_preferences: ^2.3.4
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  dotted_line: ^3.2.3
  coupon_uikit: ^0.2.1
  flutter_floating_bottom_bar: ^1.2.1+1
  video_player: ^2.9.2
  panara_dialogs: ^0.1.5
  swipee: ^0.1.0
  custom_radio_grouped_button: ^2.2.1
  flutter_slidable: ^4.0.0
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  flutter_svg_provider: ^1.0.7
  razorpay_flutter: ^1.3.7
  audioplayers: ^6.4.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  url_launcher: ^6.3.1
  action_slider: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/anim/
    - assets/images/
    - assets/audio/
    - assets/icons/

  fonts:
    - family: BonaNovaSC
      fonts:
        - asset: assets/fonts/BonaNovaSC-Bold.ttf
        - asset: assets/fonts/BonaNovaSC-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_SemiCondensed-Regular.ttf
        - asset: assets/fonts/Roboto_Condensed-Medium.ttf
        - asset: assets/fonts/Roboto_Condensed-Bold.ttf

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf